### PR TITLE
Unit test for NSMNSE-37: removeClientInterface() function

### PR DESCRIPTION
**Pull request by ziyuguo716**
This PR is a fix from https://github.com/cisco-app-networking/nsm-nse/pull/39 (Wrong branch used)

### CODE REVIEW

**Review by ana-moga — APPROVED** [review]

**Comment by CosminNechifor** [comment]
Hey @ziyuguo716 add the context to ``circleci`` so that the image gets published.

**Comment by ziyuguo716** [comment]
> Hey @ziyuguo716 add the context to `circleci` so that the image gets published.

Hi @CosminNechifor, not sure if this addresses your comment: @shanchunyang0919  created a go-test circleci job in [this PR](https://github.com/cisco-app-networking/nsm-nse/pull/38). So, we are waiting for his circleci job to get merged into the workflow for both of our unit tests

**Review by CosminNechifor — APPROVED** [review]
Why wasn't this merged is there a reason for keeping it open?

**Comment by ziyuguo716** [comment]
> Why wasn't this merged is there a reason for keeping it open?

This PR is a subtask of [NSMNSE-18](https://jira-eng-sjc4.cisco.com/jira/browse/NSMNSE-18). @shanchunyang0919 's  https://github.com/cisco-app-networking/nsm-nse/pull/38 is the other part of the unit testing for `pkg/universal-cnf/config/composite.go`. Not sure if it's necessary to merge all our tests into `composite_test.go`, considering my unit tests are now in a separate file `removeClientInterface_test.go`. What do you think @CosminNechifor @tiswanso ?

**Review by snowbldr — APPROVED** [review]

**Comment by tiswanso** [comment]
Sorry for leaving this dangling @ziyuguo716.  What's the consensus on this?  If it's not already superseded by other merges please create this PR against the wwwin-github.cisco.com repo and we can merge it in with a quicker final approval.

**Comment by ziyuguo716** [comment]
Moved to internal repo: https://wwwin-github.cisco.com/cisco-app-networking/nsm-nse/pull/8

**Pull request closed without merging**
