### PR TITLE
NSMNSE-97 Fix multiple key-value pairs with same key error

### PR DESCRIPTION
**Pull request by ondrej-fabry**
This PR fixes a bug that occurred when sending DP config to agent failed repeatedly. 

The solution is to clone DP config to local variable and only update the actual DP config after successful send to agent.

JIRA issue: [NSMNSE-97](https://jira-eng-sjc4.cisco.com/jira/browse/NSMNSE-97)

### CODE REVIEW

**Comment by ondrej-fabry** [comment]
Cannot add reviewers.. @tiswanso @shanchunyang0919 @panyuenlau @CosminNechifor please review this PR

**Comment by panyuenlau** [comment]
Looks like a clever fix to me!

**Review by snowbldr — APPROVED** [review]
LGTM

**Comment by tiswanso** [comment]
Please recreate this PR against the wwwin-github.cisco.com version and add a link back here.

**Comment by ondrej-fabry** [comment]
PR migrated to internal github: https://wwwin-github.cisco.com/cisco-app-networking/nsm-nse/pull/6

**Pull request closed without merging**
