### PR TITLE
add remove all workloads endpoint

### PR DESCRIPTION
**Pull request by vladmoisescu**
Add endpoint to remove all workloads from a connectivity domain

### CODE REVIEW

**Review by CosminNechifor — APPROVED** [review]
LGTM

**Review by mihmatache — APPROVED** [review]

**Comment by tiswanso** [comment]
So, the idea is the "finalizer" logic in the connectivity-domain operator would connect to the service-registry server and send a RemoveAllWorkloads message and wait for the reply to know it's done?

**Comment by vladmoisescu** [comment]
> So, the idea is the "finalizer" logic in the connectivity-domain operator would connect to the service-registry server and send a RemoveAllWorkloads message and wait for the reply to know it's done?

Yes, the connectivity domain CR will not be deleted until the workloads removal is successfully completed

**Comment by tiswanso** [comment]
Looks like this merged into the wwwin-github.cisco.com repo as https://wwwin-github.cisco.com/cisco-app-networking/nsm-nse/pull/1 right?

**Comment by vladmoisescu** [comment]
> Looks like this merged into the wwwin-github.cisco.com repo as https://wwwin-github.cisco.com/cisco-app-networking/nsm-nse/pull/1 right?

Right, that's why I need a new tag, to be able to import the new API

**Comment by tiswanso** [comment]
Closing this as it was merged into the wwwin-github.cisco.com repo.

**Pull request closed without merging**
